services:
  - type: web
    name: shopsmart-backend
    env: node
    root: server
    buildCommand: npm install && npx prisma generate
    startCommand: node src/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
